title: Page de Maxime Dion
author: Maxime Dion
email: maxime.dion@usherbrooke.ca
description: >- # this means to ignore newlines until "baseurl:"
    Développeur quantique et chargé de cours
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oneminimax.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  oneminimax
linkedin_username: maxime-dion-49449965

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate